### ISSUE TITLE
Unable to take pictures using Picture class

### ISSUE THREAD

**Issue by lum0s** [HackerDM/Home-Automation#8]
@rishab178 Videos class is working fine. I am able to run the shell script using the method in Video class. But I have no clue why it is not working for the Picture class. Kindly look into it.

**Comment by rishab178** [comment]
Did you try using Open CV for it?
You had a open CV code running, right?
Try making a shell script to run that and then run the shell script from the Java class.
I'll try running the existing fswebcam code. Some issues with the drivers installed maybe. It did run when I tried it a week ago.

Also update the Readme file [ https://github.com/HackerDM/Home-Automation/edit/master/README.md ] with the current IP address for the Pi.

**Comment by lum0s** [comment]
I created an issue for all the details. I don't want these details to be in the readme file. Yeah I did have an opencv code running. I ll try that and get back to you on this.

**Comment by rishab178** [comment]
Shit. Sorry! I just updated the Readme file with the details! :tongue: 
if you want to then do revert back the changes. :smile:
